# Generated by Django 2.0.3 on 2018-04-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_startdate', models.CharField(default='', max_length=255)),
                ('booking_enddate', models.CharField(default='', max_length=255)),
                ('pickup_point', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('reviews', models.CharField(max_length=255, null=True)),
                ('booking_isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_password', models.CharField(default='', max_length=500)),
                ('user_email', models.EmailField(default='', max_length=255, primary_key=True, serialize=False)),
                ('user_mobile', models.CharField(default='', max_length=255)),
                ('user_dob', models.CharField(default='', max_length=255)),
                ('user_image', models.CharField(max_length=255, null=True)),
                ('user_isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_roleid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.UserRole'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='staff.vehicles'),
        ),
    ]
