# Generated by Django 2.0.3 on 2018-05-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_iscancel',
            field=models.BooleanField(default=True),
        ),
    ]
