# Generated by Django 2.0.3 on 2018-05-03 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking_booking_iscancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelcharges',
            fields=[
                ('cancel_id', models.AutoField(primary_key=True, serialize=False)),
                ('pending_charges', models.IntegerField(default='')),
                ('cancel_isactive', models.BooleanField(default=True)),
                ('booking_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.booking')),
                ('user_email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
