# Generated by Django 2.0.3 on 2018-05-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cancelcharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_iscancel',
            field=models.BooleanField(default=False),
        ),
    ]
