# Generated by Django 2.0.3 on 2018-05-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180503_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='con_password',
            field=models.CharField(default='', max_length=500),
        ),
    ]
