# Generated by Django 2.0.3 on 2018-05-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_con_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='con_password',
        ),
    ]
