# Generated by Django 2.0.3 on 2018-04-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='', max_length=255)),
                ('company_isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_types',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(default='', max_length=255)),
                ('type_price', models.IntegerField(default='')),
                ('type_isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(default='', max_length=255)),
                ('vehicle_description', models.CharField(default='', max_length=255)),
                ('vehicle_image', models.CharField(max_length=255, null=True)),
                ('vehicles_isactive', models.BooleanField(default=True)),
                ('company_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='staff.vehicle_company')),
                ('type_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='staff.vehicle_types')),
            ],
        ),
    ]
