# Generated by Django 2.0.3 on 2018-05-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='vehicle_isavaliable',
            field=models.BooleanField(default=True),
        ),
    ]
