# Generated by Django 2.0.3 on 2018-05-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_vehicles_vehicle_isavaliable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='u_email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
