# Generated by Django 2.0.3 on 2018-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_vehicles_u_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='u_email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
